<?php
require_once "tests/upgrade/UpgradeTestCase.php";

class RebuildActivitiesDashboardsTest extends UpgradeTestCase
{
    public function setUp()
    {
        $this->withFile = 'modules/ut_with/clients/base/views/history/history.php';
        $this->withoutFile = 'modules/ut_without/clients/base/views/history/history.php';

        parent::setUp();
        SugarTestHelper::setUp('files');
        mkdir_recursive(dirname($this->withFile));
        mkdir_recursive(dirname($this->withoutFile));
        file_put_contents($this->withFile,'<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata(\'view\',\'history\');
$coreDefs[\'dashlets\'][0][\'filter\'][\'module\'] = array(\'ut_with\');
$coreDefs[\'tabs\'][0][\'link\'] = \'ut_with_activities_meetings\';
$coreDefs[\'tabs\'][1][\'link\'] = \'ut_with_activities_emails\';
$coreDefs[\'tabs\'][2][\'link\'] = \'ut_with_activities_calls\';
$coreDefs[\'custom_toolbar\'][\'buttons\'][0][\'buttons\'][0][\'params\'][\'link\'] = \'ut_with_activities_meetings\';
$coreDefs[\'custom_toolbar\'][\'buttons\'][0][\'buttons\'][1][\'params\'][\'link\'] = \'ut_with_activities_emails\';
$coreDefs[\'custom_toolbar\'][\'buttons\'][0][\'buttons\'][2][\'params\'][\'link\'] = \'ut_with_activities_calls\';
$viewdefs[\'ut_with\'][\'base\'][\'view\'][\'history\'] = $coreDefs;
');

        file_put_contents($this->withoutFile,'<?php
// This wasn\'t autogenerated by activites relationship
$viewdefs = array(\'never_gonna\'=>\'give you up\');
');
    }

    public function tearDown()
    {
        parent::tearDown();
        SugarTestHelper::tearDown();
        rmdir_recursive('modules/ut_with');
        rmdir_recursive('modules/ut_without');
    }

    /**
     * Test to make sure the new dashboards are created and the old one isn't there anymore
     */
    public function testUpgradeDashboards()
    {
        $script = $this->upgrader->getScript('post', '7_RebuildActivitiesDashboards');
        $script->from_version = '7.1.5';
        $script->run();

        
        $this->assertFileExists($this->withFile, 'History file is gone after upgrade in upgraded history.');
        $this->assertFileExists($this->withoutFile, 'History file is gone after upgrade in non-upgrade history.');
        
        $viewdefs = array();
        $coreDefs = array();
        require($this->withFile);
        $this->assertCount(1, $viewdefs['ut_with']['base']['view']['history']['custom_toolbar']['buttons'][0]['buttons'], "History file was not upgraded correctly, too many custom_toolbar buttons");

        
        $viewdefs = array();
        $coreDefs = array();
        require($this->withoutFile);
        $this->assertEquals('give you up', $viewdefs['never_gonna'], "The unupgraded files are going to give me up and or let me down and or run around and desert me.");

    }
}
