<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

require_once('modules/Contracts/Contract.php');

class Bug48475Test extends Sugar_PHPUnit_Framework_TestCase
{
    var $contractType;
    var $contract;

	public function setUp()
	{
		include('include/modules.php');
	    $GLOBALS['beanList'] = $beanList;
	    $GLOBALS['beanFiles'] = $beanFiles;
	    $GLOBALS['current_user'] = SugarTestUserUtilities::createAnonymousUser();
        $GLOBALS['current_user']->is_admin = 1;
	}

	public function tearDown()
	{
		SugarTestUserUtilities::removeAllCreatedAnonymousUsers();
	}

	public function testContractCreateNewListQuery()
	{
        $this->contract = new Contract();
        $sql = $this->contract->create_new_list_query('', '');
        $results = $GLOBALS['db']->query($sql, false);
        $this->assertFalse($GLOBALS['db']->checkError(), 'Assert that the SQL statement generated by create_new_list_query did not cause an error');
    }

}

?>
