<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN {{$class.name}}
 */

{{foreach from=$class.requires item='require'}}
require_once('{{$require}}');
{{/foreach}}

class {{$class.name}}_sugar extends {{$class.extends}} {
	var $new_schema = true;
	var $module_dir = '{{$class.name}}';
	var $object_name = '{{$class.name}}';
	var $table_name = '{{$class.table_name}}';
	var $importable = {{if $class.importable}}true{{else}}false{{/if}};
	{{foreach from=$class.fields key='field' item='def'}}
	var ${{$field}};
	{{/foreach}}
	{{if empty($class.team_security)}}
	var $disable_row_level_security = true;
	{{/if}}
	function {{$class.name}}_sugar(){	
		parent::{{$class.extends}}();
	}
	
	{{if $class.acl}}
function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
	{{/if}}
	
}
?>
