<?php

require_once 'data/SugarACLStrategy.php';

/**
 * Test class for SugarACLStrategy.
 * Generated by PHPUnit on 2012-04-05 at 18:11:37.
 */
class SugarACLStrategyTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SugarACLStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('SugarACLStrategy');
    }

    /**
     * @covers SugarACLStrategy::getCurrentUser
     */
    public function testGetCurrentUser()
    {
        // Remove the following lines when you implement this test.
        $user1 = $this->getMock('User');
        $context = array('user' => $user1);
        $user2 = $this->getMock('User');

        $this->assertEquals($user1, $this->object->getCurrentUser($context));
        unset($GLOBALS['current_user']);
        $this->assertNull($this->object->getCurrentUser(array()));

        $GLOBALS['current_user'] = $user2;
        $this->assertEquals($user2, $this->object->getCurrentUser(array()));

        $this->assertEquals($user1, $this->object->getCurrentUser($context));

    }

    /**
     * @covers SugarACLStrategy::getUserID
     */
    public function testGetUserID()
    {
        $user1 = $this->getMock('User');
        $user2 = $this->getMock('User');

        $user1->id = 111;
        $user2->id = 222;

        $this->assertNull($this->object->getUserID(array()));

        $GLOBALS['current_user'] = $user2;

        $this->assertEquals($user2->id, $this->object->getUserID(array()));

        $this->assertEquals($user1->id, $this->object->getUserID(array('user' => $user1)));

        $this->assertEquals(333, $this->object->getUserID(array('user_id' => 333)));

        $this->assertEquals($user1->id, $this->object->getUserID(array('user_id' => 333, 'user' => $user1)));
    }
}
?>
